#!/bin/bash
set -euo pipefail
set -x
mkdir "$1"
cd "$1"
mkdir -p bin out/manifests out/configmaps

KUBECTL_VERSION=1.17.2
curl -Lsfo bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
chmod a+x bin/kubectl

JSONNET_VERSION=0.14.0
curl -Lsf https://github.com/google/jsonnet/releases/download/v${JSONNET_VERSION}/jsonnet-bin-v${JSONNET_VERSION}-linux.tar.gz | \
  tar -C bin/ -xzvf -

JB_VERSION=0.2.0
curl -Lsfo bin/jb \
  https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v${JB_VERSION}/jb-linux-amd64
chmod a+x bin/jb

KUBERNETS_MIXIN_VERSION=0.3
pushd /kubernetes-mixin
jb init
jb install github.com/kubernetes-monitoring/kubernetes-mixin@release-${KUBERNETS_MIXIN_VERSION}
jsonnet -J vendor -S -e 'std.manifestYamlDoc((import "mixin.libsonnet").prometheusAlerts)' > \
  kubernetes-mixin-alerts.yaml
jsonnet -J vendor -S -e 'std.manifestYamlDoc((import "mixin.libsonnet").prometheusRules)' > \
  kubernetes-mixin-rules.yaml
mkdir grafana-dashboards/
jsonnet -J vendor -m grafana-dashboards/ -e '(import "mixin.libsonnet").grafanaDashboards'
popd
mkdir -p out/configmaps/prometheus/{prometheus,grafana-dashboards}
cp -r /kubernetes-mixin/kubernetes-mixin-*.yaml out/configmaps/prometheus/prometheus/
cp -r /kubernetes-mixin/grafana-dashboards out/configmaps/prometheus/grafana-dashboards-kubernetes-mixins

#
find out
