#!/bin/bash
set -euo pipefail
site=$1
args="${2:-$site.args}"
out="${args%%.args}"

jsonnet=${JSONNET:-jsonnet}
opts=""
[[ -s "$args" ]] && opts=($(cat "$args"))

eval --  "$jsonnet" "${opts[@]}" -J vendor/ -J . "$site" -S -c -m "build/$out"
