#!/bin/bash
set -euo pipefail
site=$1
args="${2:-$site.args}"
out="${args%%.args}"

jsonnet=${JSONNET:-jsonnet}
opts=""
[[ -s "$args" ]] && opts=($(cat "$args"))

rm -rf "build/$out"
eval --  "$jsonnet" "${opts[@]}" --ext-code-file "jsonnetfile_lock=jsonnetfile.lock.json" -J vendor/ -J vendor-local/ "$site" -S -c -m "build/$out"
