apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-k8s-webhook-handler-
  namespace: ci
spec:
  entrypoint: build
  securityContext:
    runAsUser: 1000
  volumes:
    - name: pass-gpg
      secret:
        secretName: 5pi-home-pass-gpg-key
  templates:
    - name: build
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
              repo: "https://github.com/5pi-home/home.git"
              revision: "{{workflow.annotations.k8s-webhook-handler.io/revision}}"
          - name: pass
            path: /home/user/.password-store
            git:
              repo: https://github.com/5pi-home/pass.git
              revision: main
              usernameSecret:
                name: k8s-webhook-handler
                key: github-username
              passwordSecret:
                name: k8s-webhook-handler
                key: github-token
      metadata:
        annotations:
          container.apparmor.security.beta.kubernetes.io/main: unconfined
      nodeSelector:
        "kubernetes.io/arch": amd64
      script:
        image: registry.d.42o.de/home:be0ae31483
        workingDir: /src
        command: [bash]
        volumeMounts:
          - mountPath: /home/user/pass-gpg
            name: pass-gpg
        source: |
          jb install
          gpg --import < /home/user/pass-gpg/gpg-key
          FPL_LOCAL=false ./generate site.jsonnet

      outputs:
        artifacts:
        - name: manifests
          path: /src/build
